// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"go.uber.org/zap"
	"management/internal/adapter/config"
	"management/internal/adapter/storage/postgres"
	http2 "management/internal/adapter/transport/http"
	"management/internal/core/attribute"
	"management/internal/core/port/db"
	"management/internal/core/port/department"
	"management/internal/core/port/http"
	"management/internal/core/port/user"
	"management/internal/core/service"
	"sync"
)

// Injectors from wire.go:

func InitApp(ctx context.Context, wg *sync.WaitGroup, rw *sync.RWMutex, Cfg *config.Container) (*App, func(), error) {
	postgresEngineMaker, cleanup, err := dbEngineFunc(ctx, Cfg)
	if err != nil {
		return nil, nil, err
	}
	userRepositoryPort := psql.NewUserRepository(postgresEngineMaker)
	userServicePort := service.NewUserService(userRepositoryPort)
	departmentRepositoryPort := psql.NewDepartmentRepository(postgresEngineMaker)
	departmentServicePort := service.NewDepartmentService(departmentRepositoryPort)
	attributeRepositoryPort := psql.NewAttributeRepository(postgresEngineMaker)
	attributeServicePort := service.NewAttributeService(attributeRepositoryPort)
	serverMaker, cleanup2, err := httpServerFunc(ctx, Cfg, userServicePort, departmentServicePort, attributeServicePort)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := New(rw, Cfg, serverMaker, postgresEngineMaker, userRepositoryPort, userServicePort, departmentRepositoryPort, departmentServicePort, attributeRepositoryPort, attributeServicePort)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(
	ctx context.Context,
	Cfg *config.Container) (db.PostgresEngineMaker, func(), error) {
	psqlDb := psql.NewDB(Cfg)
	err := psqlDb.Start(ctx)
	if err != nil {
		zap.S().Fatal("failed to start db:", err)
	}

	if err != nil {
		zap.S().Fatal("failed to migrate db:", err)
	}
	return psqlDb, func() { psqlDb.Close(ctx) }, nil
}

func httpServerFunc(
	ctx context.Context,
	Cfg *config.Container,
	userService user.UserServicePort,
	departmentService department.DepartmentServicePort,
	attributeService attribute.AttributeServicePort,
) (http.ServerMaker, func(), error) {
	httpServer := http2.NewHTTPServer(ctx, Cfg, userService, departmentService, attributeService)
	err := httpServer.Start(ctx)
	if err != nil {
		return nil, nil, err
	}
	return httpServer, func() { httpServer.Close(ctx) }, nil
}
