CREATE TABLE fuels (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    situation BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transmissions (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    situation BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE colors (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    color_code VARCHAR(10) NOT NULL,
    situation BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE models(
    id VARCHAR(255) PRIMARY KEY,
    brand_id INT NOT NULL REFERENCES brands(id)
    name VARCHAR(100) NOT NULL,
    situation BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE brands (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    situation BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cars (
    id VARCHAR(255) PRIMARY KEY,
    plate VARCHAR(20) NOT NULL,
    model_year INT NOT NULL,
    km INT NOT NULL,
    brand_id INT NOT NULL REFERENCES brands(id),
    model_id INT NOT NULL REFERENCES models(id),
    color_id INT NOT NULL REFERENCES colors(id),
    fuel_id INT NOT NULL REFERENCES fuel_types(id),
    transmission_id INT NOT NULL REFERENCES transmissions(id),
    situation BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
